### ISSUE TITLE
Another open source alternative (Discussion)

### ISSUE THREAD

**Issue by mannprerak2** [connor-makowski/type_enforced#1]
Hi, good effort, but.. why not just use https://github.com/RussBaz/enforce

P.S Feel free to close this.

**Comment by connor-makowski** [comment]
Thanks for the feedback. I am not opposed to using another project, however, this project met some unique needs for me that I was not able to find elsewhere. With that said, I will have to dive into how that project solves some of the issues I want to provide in the future.
