### ISSUE TITLE
typing.Union[List,str] not supported

### ISSUE THREAD

**Issue by fenchu** [connor-makowski/type_enforced#18]
```
@type_enforced.Enforcer
def update_users_group(myenv:str, group:str, ssn:Union[list,str], op:str='list', access_token:str=None, ok500:bool=True):
    """ add or remove user or a list of users to group """
```
giving:
```
FAILED tests/test_02_scim.py/test04_groups[test1] - TypeError: (update_users_group): Type mismatch for typed variable `ssn`. Expected one of the following `[typing.Union[list, str]]` but got `<class 'str'>` instead.
```
[Union Doc](https://docs.python.org/3/library/typing.html#typing.Union)

**Comment by connor-makowski** [comment]
Thanks for creating a ticket and reporting this.

In `type_enforced`, `Union` should not be used. Check out the docs here: https://github.com/connor-makowski/type_enforced#getting-started

Specifically:

```
You can pass multiple types in brackets to validate one of multiple types. For example, you could validate an input was an int or a float with [int, float].
```

In this case, you should be able to pass in your Union statement simply as a list. EG:

```
@type_enforced.Enforcer
def update_users_group(myenv:str, group:str, ssn:[list,str], op:str='list', access_token:str=None, ok500:bool=True):
    """ add or remove user or a list of users to group """
```

Let me know if this does not resolve your issue.

**Comment by connor-makowski** [comment]
Closing this issue. Feel free to reopen it if you feel that your issue was not handled.

**Comment by fenchu** [comment]
This works fine, I'm just used to `Union[List,str]` but easier to write `[list,str] Works great. Thanks
