### ISSUE TITLE
Non-standard syntax for multiple types of one parameter

### ISSUE THREAD

**Issue by stardust85** [connor-makowski/type_enforced#21]
Package version: 0.0.16
Python version: 3.10.6

code:
```python
from type_enforced import Enforcer

@Enforcer
def my_func(first: int | None = None):
    print(first)

my_func()
```

expected output:
```
None
```
current output:
```
Traceback (most recent call last):
  File "/home/ms580j/leam/backend/utils/export/type_enforced_bug.py", line 7, in <module>
    my_func()
  File "/home/ms580j/.local/share/virtualenvs/export-pPyZbvWm/lib/python3.10/site-packages/type_enforced/enforcer.py", line 96, in __call__
    self.__check_type__(assigned_vars.get(key), value, key)
  File "/home/ms580j/.local/share/virtualenvs/export-pPyZbvWm/lib/python3.10/site-packages/type_enforced/enforcer.py", line 118, in __check_type__
    self.__exception__(
  File "/home/ms580j/.local/share/virtualenvs/export-pPyZbvWm/lib/python3.10/site-packages/type_enforced/enforcer.py", line 34, in __exception__
    raise TypeError(f"({self.__fn__.__qualname__}): {message}")
TypeError: (my_func): Type mismatch for typed variable `first`. Expected one of the following `[int | None]` but got `<class 'NoneType'>` instead.
```

The same error happens when I use ```def my_func(first: Optional[int] = None):``` or ```def my_func(first: Union[int, None] = None):``` where Optional and Union are imported from typing module.

It works with ```def my_func(first: [int, None] = None)```, but it is different than what is mentioned in Python documentation:
https://docs.python.org/3/library/typing.html#typing.Optional
https://docs.python.org/3/library/stdtypes.html#types-union

**Comment by connor-makowski** [comment]
Unfortunately type_enforced does not follow the standard python typing process but uses a slightly modified version. The main readme docs should cover what is accepted.

Future major versions of type_enforced might add some support, however these are purely decorators from python"s perspective unless you run an external python variant like mypy. In terms of how these external variants work under the hood, it's mostly spaghetti code to enable a swath of changing pep standards.

As of right now, type_enforced runs with minimal code as a pure python implementation with no dependencies. The goal is to preserve that aspect.

This will depend on me having enough free time or an outside collaborator stepping up and making a PR.

**Comment by connor-makowski** [comment]
For now, I am going to consider this a wontfix and close it out. In the future, supporting various type hints as specified in the python docs will be considered.
