### ISSUE TITLE
importerror since 1.0.0

### ISSUE THREAD

**Issue by veenstrajelmer** [connor-makowski/type_enforced#24]
We recently introduced `type_enforced` in one of our packages where many others depend on. In the testbanks get importerrors since the release of `type_enforced 1.0.0`.

```
C:\Miniconda3\envs\hydromt-delft3dfm\lib\site-packages\meshkernel\meshkernel.py:18: in <module>
    import type_enforced
C:\Miniconda3\envs\hydromt-delft3dfm\lib\site-packages\type_enforced\__init__.py:3: in <module>
    from .enforcer import Enforcer, FunctionMethodEnforcer
C:\Miniconda3\envs\hydromt-delft3dfm\lib\site-packages\type_enforced\enforcer.py:1: in <module>
    from types import FunctionType, MethodType, GenericAlias, UnionType
E   ImportError: cannot import name 'UnionType' from 'types' (C:\Miniconda3\envs\hydromt-delft3dfm\lib\types.py)
```

This happens in several python versions, but at least py 3.9

Would it be possible to fix this, and include online testing on github?

**Comment by connor-makowski** [comment]
Thanks for the feedback.

1) For an immediate fix, can you lock to 0.0.16
2) Let me see if I can reproduce this. Then I can add a fix and add some
future tests to prevent this from happening in the future.

Connor

**Comment by connor-makowski** [comment]
Can you confirm that this is resolved for you? Feel free to close the issue if it is.

**Comment by veenstrajelmer** [comment]
It seems to be resolved indeed, the imports work again. Thanks for the quick action.
