### ISSUE TITLE
Ability to undecorate the specific class method

### ISSUE THREAD

**Issue by Ashark** [connor-makowski/type_enforced#26]
I have decorated the whole class with this:

```python
import type_enforced


@type_enforced.Enforcer
class MyClass():
    def __init__(self):
        ...
    
    def method1(self):
        ...
    
    def method2(self):
        ...
```
This is convenient, because I do not need to add this decorator to each class's method.

But sometimes I want to disable the decoration for the specific method, while still keeping the decoration for all other methods (again, for convenience). For example, it may be useful for [false positive](https://github.com/connor-makowski/type_enforced/issues/25) detection workarounding.

Is it possible to "undecorate" the specific method? Something like this:
```python
@type_enforced.Enforcer
class MyClass():
    def __init__(self):
        ...
    
    
    def method1(self):
        ...
    
    @type_enforced.Enforcer(disable=True)
    def method2(self):
        ...
```

**Comment by connor-makowski** [comment]
Tagging: https://github.com/connor-makowski/type_enforced/commit/7ba73625f214656586e40dd8fb52a139e771836b

**Comment by connor-makowski** [comment]
Tagging: https://github.com/connor-makowski/type_enforced/commit/67ecd6c6c1bdfbea9b296c644c2a6aaf49908f8b
