### ISSUE TITLE
Incorrectly recognized `Callable` type

### ISSUE THREAD

**Issue by Ashark** [connor-makowski/type_enforced#29]
Hello. I have a problem when annotating a function that returns another function:

```python
import type_enforced
from typing import Callable


@type_enforced.Enforcer
def greet(name: str) -> Callable:
    def inner() -> str:
        return f"Hello, {name}!"
    
    return inner


greeter = greet("Alice")

print(greeter())
```

Gives the error:
```
TypeError: (greet): Type mismatch for typed variable `return`. Expected one of the following `[typing.Callable]` but got `<class 'function'>` instead.
```

Such annotation did the workaround, but it is a crutch: `def greet(name: str) -> type(lambda x: x):`.

**Comment by conmakMIT** [comment]
According to the docs [here](https://github.com/connor-makowski/type_enforced?tab=readme-ov-file#supported-type-checking-features), Callable is not supported.

However, this is a great feature request.

**Comment by connor-makowski** [comment]
According to the docs [here](https://github.com/connor-makowski/type_enforced?tab=readme-ov-file#supported-type-checking-features), Callable is not supported.

However, this is a great feature request.
