### ISSUE TITLE
Provide ability to manually specify expected types instead of annotated

### ISSUE THREAD

**Issue by Ashark** [connor-makowski/type_enforced#32]
I would like to use normal annotations in my project, while taking advantage of runtime checks with type-enforced.

Unfortunately, it has some false positive detection. Examples are: #29, #31.

I wanted the #26 to be implemented for these cases as a workaround.  But I now thought that it will not be either a good solution, because for disabled methods I will loose the advantage of checks.

Let's maybe introduce a way to override normal expected cases? I.e., to say type-enforced that when it sees some type, defined in the `override_recognition` dict, it should instead check against  the value for such key.
For example, I can have such config file:
```python
override_recognition = {
    "Callable": type(lambda x: x)
    "TextIO": StringIO | TextIOWrapper
    "Developer": WithSubclasses(Developer)
}
```

This way I could easily disable/enable type-enforcer when needed, without editing the type hints (because when disabling, I need to remove WithSubclasses hack). I am [using](https://invent.kde.org/ashark/kde-builder/-/blob/master/ksblib/Util/Conditional_Type_Enforced.py?ref_type=heads) my own decorator over your type_enforced, called `@conditional_type_enforced`, with the approach taken from [here](https://stackoverflow.com/q/14636350/7869636).

If this is done, I could get rid of ugly type hints like this: `-> list[Module | Union[*WithSubclasses(ModuleSet)]]` and just use them like normal `-> list[Module | ModuleSet]`

**Comment by connor-makowski** [comment]
This is an interesting suggestion. I think this might be achievable and make sense as part of a larger type_enforced construct to enable/disable it. Let me think about some of the larger implications around this and try some code variations. Also keep in mind that I need to keep backwards compatibility.

**Comment by connor-makowski** [comment]
In 1.4.0: `Callable` support was added as was support for an `enabled` in `Enforcer`. This is still outstanding. This requires more time and thought.

**Comment by connor-makowski** [comment]
Closing this issue.
